/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValidateImport } from './routes/validate'
import { Route as LicensedImport } from './routes/_licensed'
import { Route as IndexImport } from './routes/index'
import { Route as LicensedEspImport } from './routes/_licensed.esp'

// Create/Update Routes

const ValidateRoute = ValidateImport.update({
  path: '/validate',
  getParentRoute: () => rootRoute,
} as any)

const LicensedRoute = LicensedImport.update({
  id: '/_licensed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LicensedEspRoute = LicensedEspImport.update({
  path: '/esp',
  getParentRoute: () => LicensedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_licensed': {
      id: '/_licensed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LicensedImport
      parentRoute: typeof rootRoute
    }
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateImport
      parentRoute: typeof rootRoute
    }
    '/_licensed/esp': {
      id: '/_licensed/esp'
      path: '/esp'
      fullPath: '/esp'
      preLoaderRoute: typeof LicensedEspImport
      parentRoute: typeof LicensedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LicensedRoute: LicensedRoute.addChildren({ LicensedEspRoute }),
  ValidateRoute,
})

/* prettier-ignore-end */
