/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValidateImport } from './routes/validate'
import { Route as EspImport } from './routes/esp'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ValidateRoute = ValidateImport.update({
  path: '/validate',
  getParentRoute: () => rootRoute,
} as any)

const EspRoute = EspImport.update({
  path: '/esp',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/esp': {
      id: '/esp'
      path: '/esp'
      fullPath: '/esp'
      preLoaderRoute: typeof EspImport
      parentRoute: typeof rootRoute
    }
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esp': typeof EspRoute
  '/validate': typeof ValidateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esp': typeof EspRoute
  '/validate': typeof ValidateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/esp': typeof EspRoute
  '/validate': typeof ValidateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/esp' | '/validate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/esp' | '/validate'
  id: '__root__' | '/' | '/esp' | '/validate'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspRoute: typeof EspRoute
  ValidateRoute: typeof ValidateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspRoute: EspRoute,
  ValidateRoute: ValidateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/esp",
        "/validate"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/esp": {
      "filePath": "esp.tsx"
    },
    "/validate": {
      "filePath": "validate.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
