/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ValidateImport } from './routes/validate'
import { Route as EspImport } from './routes/esp'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ValidateRoute = ValidateImport.update({
  path: '/validate',
  getParentRoute: () => rootRoute,
} as any)

const EspRoute = EspImport.update({
  path: '/esp',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/esp': {
      id: '/esp'
      path: '/esp'
      fullPath: '/esp'
      preLoaderRoute: typeof EspImport
      parentRoute: typeof rootRoute
    }
    '/validate': {
      id: '/validate'
      path: '/validate'
      fullPath: '/validate'
      preLoaderRoute: typeof ValidateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  EspRoute,
  ValidateRoute,
})

/* prettier-ignore-end */
